version = 0.1

[default.deploy.parameters]
stack_name = "payflow-dev"
region = "ca-central-1"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=dev"
confirm_changeset = false
fail_on_empty_changeset = false
